python main.py --env-id AdventureNoFrameskip-v4 --update_after_ep
python main.py --env-id AirRaidNoFrameskip-v4 --update_after_ep
python main.py --env-id AlienNoFrameskip-v4 --update_after_ep
python main.py --env-id AmidarNoFrameskip-v4 --update_after_ep
python main.py --env-id AssaultNoFrameskip-v4 --update_after_ep
python main.py --env-id AsterixNoFrameskip-v4 --update_after_ep
python main.py --env-id AsteroidsNoFrameskip-v4 --update_after_ep
python main.py --env-id AtlantisNoFrameskip-v4 --update_after_ep
python main.py --env-id BankHeistNoFrameskip-v4 --update_after_ep
python main.py --env-id BattleZoneNoFrameskip-v4 --update_after_ep
python main.py --env-id BeamRiderNoFrameskip-v4 --update_after_ep
python main.py --env-id BerzerkNoFrameskip-v4 --update_after_ep
python main.py --env-id BowlingNoFrameskip-v4 --update_after_ep
python main.py --env-id BoxingNoFrameskip-v4 --update_after_ep
python main.py --env-id BreakoutNoFrameskip-v4 --update_after_ep
python main.py --env-id CarnivalNoFrameskip-v4 --update_after_ep
python main.py --env-id CentipedeNoFrameskip-v4 --update_after_ep
python main.py --env-id ChopperCommandNoFrameskip-v4 --update_after_ep
python main.py --env-id CrazyClimberNoFrameskip-v4 --update_after_ep
python main.py --env-id DefenderNoFrameskip-v4 --update_after_ep
python main.py --env-id DemonAttackNoFrameskip-v4 --update_after_ep
python main.py --env-id DoubleDunkNoFrameskip-v4 --update_after_ep
python main.py --env-id ElevatorActionNoFrameskip-v4 --update_after_ep
python main.py --env-id EnduroNoFrameskip-v4 --update_after_ep
python main.py --env-id FishingDerbyNoFrameskip-v4 --update_after_ep
python main.py --env-id FreewayNoFrameskip-v4 --update_after_ep
python main.py --env-id FrostbiteNoFrameskip-v4 --update_after_ep
python main.py --env-id GopherNoFrameskip-v4 --update_after_ep
python main.py --env-id GravitarNoFrameskip-v4 --update_after_ep
python main.py --env-id HeroNoFrameskip-v4 --update_after_ep
python main.py --env-id IceHockeyNoFrameskip-v4 --update_after_ep
python main.py --env-id JamesbondNoFrameskip-v4 --update_after_ep
python main.py --env-id JourneyEscapeNoFrameskip-v4 --update_after_ep
python main.py --env-id KangarooNoFrameskip-v4 --update_after_ep
python main.py --env-id KrullNoFrameskip-v4 --update_after_ep
python main.py --env-id KungFuMasterNoFrameskip-v4 --update_after_ep
python main.py --env-id MontezumaRevengeNoFrameskip-v4 --update_after_ep
python main.py --env-id AmidarNoFrameskip-v4 --update_after_ep
python main.py --env-id AmidarNoFrameskip-v4 --update_after_ep
python main.py --env-id AmidarNoFrameskip-v4 --update_after_ep
python main.py --env-id AdventureNoFrameskip-v4 --update_after_ep
python main.py --env-id AirRaidNoFrameskip-v4 --update_after_ep
python main.py --env-id AlienNoFrameskip-v4 --update_after_ep
python main.py --env-id AmidarNoFrameskip-v4 --update_after_ep
python main.py --env-id AmidarNoFrameskip-v4 --update_after_ep
python main.py --env-id AmidarNoFrameskip-v4 --update_after_ep
python main.py --env-id AmidarNoFrameskip-v4 --update_after_ep
python main.py --env-id AmidarNoFrameskip-v4 --update_after_ep
python main.py --env-id AmidarNoFrameskip-v4 --update_after_ep
python main.py --env-id AmidarNoFrameskip-v4 --update_after_ep
python main.py --env-id AdventureNoFrameskip-v4 --update_after_ep
python main.py --env-id MsPacmanNoFrameskip-v4 --update_after_ep
python main.py --env-id NameThisGameNoFrameskip-v4 --update_after_ep
python main.py --env-id MsPacmanNoFrameskip-v4 --update_after_ep
python main.py --env-id PhoenixNoFrameskip-v4 --update_after_ep
python main.py --env-id PitfallNoFrameskip-v4 --update_after_ep
python main.py --env-id PongNoFrameskip-v4 --update_after_ep
python main.py --env-id PooyanNoFrameskip-v4 --update_after_ep
python main.py --env-id PrivateEyeNoFrameskip-v4 --update_after_ep
python main.py --env-id QbertNoFrameskip-v4 --update_after_ep
python main.py --env-id RiverraidNoFrameskip-v4 --update_after_ep
python main.py --env-id RoadRunnerNoFrameskip-v4 --update_after_ep
python main.py --env-id RobotankNoFrameskip-v4 --update_after_ep
python main.py --env-id SeaquestNoFrameskip-v4 --update_after_ep
python main.py --env-id SkiingNoFrameskip-v4 --update_after_ep
python main.py --env-id SolarisNoFrameskip-v4 --update_after_ep
python main.py --env-id SpaceInvadersNoFrameskip-v4 --update_after_ep
python main.py --env-id StarGunnerNoFrameskip-v4 --update_after_ep
python main.py --env-id TennisNoFrameskip-v4 --update_after_ep
python main.py --env-id TimePilotNoFrameskip-v4 --update_after_ep
python main.py --env-id TutankhamNoFrameskip-v4 --update_after_ep
python main.py --env-id UpNDownNoFrameskip-v4 --update_after_ep
python main.py --env-id VentureNoFrameskip-v4 --update_after_ep
python main.py --env-id VideoPinballNoFrameskip-v4 --update_after_ep
python main.py --env-id WizardOfWorNoFrameskip-v4 --update_after_ep
python main.py --env-id YarsRevengeNoFrameskip-v4 --update_after_ep
python main.py --env-id ZaxxonNoFrameskip-v4 --update_after_ep